-- SmartCart: core schema (Phase 1)
-- Derived from the existing frontend data model (products, categories, cart,
-- wishlist, addresses, coupons, orders, reviews, returns, promo banner).

-- ---------------------------------------------------------------- helpers
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------------------------------------------------------------- profiles
-- One row per auth.users row. Created by trigger (see security migration).
create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  name        text not null default '',
  email       text not null default '',
  phone       text,
  role        text not null default 'customer' check (role in ('customer', 'admin')),
  status      text not null default 'Active'   check (status in ('Active', 'Blocked')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index profiles_role_idx on public.profiles (role);
create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- -------------------------------------------------------------- categories
-- The frontend identifies a category by its name string (e.g. 'under 40 rupee').
create table public.categories (
  id           bigint generated always as identity primary key,
  name         text not null,
  icon         text not null default '🍽️',
  description  text not null default '',
  status       text not null default 'Active' check (status in ('Active', 'Inactive')),
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create unique index categories_name_uq on public.categories (lower(name));
create trigger categories_updated_at before update on public.categories
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- products
-- ids are kept from list.json (1..N) because /product/:id, carts and wishlists
-- reference them. `generated by default` lets the seed insert explicit ids.
create table public.products (
  id                 bigint generated by default as identity primary key,
  name               text not null check (length(btrim(name)) > 0),
  title              text not null default '',           -- short description (list.json "title")
  price              numeric(10,2) not null check (price >= 0),
  discount_percent   integer not null default 0 check (discount_percent between 0 and 90),
  -- same formula as the old buildProduct(): originalPrice = round(price / (1 - d/100))
  original_price     numeric(10,2) generated always as (
                       case when discount_percent > 0
                            then round(price / (1 - discount_percent / 100.0))
                            else price end
                     ) stored,
  image              text not null default '',
  category_id        bigint not null references public.categories(id) on delete restrict,
  stock_count        integer not null default 0 check (stock_count >= 0),
  -- Catalog baseline rating (frozen from the old generated values). Real approved
  -- reviews are blended on top of it in the catalog_products view.
  base_rating        numeric(2,1) not null default 0 check (base_rating between 0 and 5),
  base_review_count  integer not null default 0 check (base_review_count >= 0),
  specs              jsonb not null default '{}'::jsonb,
  is_best_seller     boolean not null default false,
  is_trending        boolean not null default false,
  is_active          boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index products_category_idx on public.products (category_id);
create index products_active_idx   on public.products (is_active);
create trigger products_updated_at before update on public.products
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------- product_reviews
create table public.product_reviews (
  id          bigint generated always as identity primary key,
  product_id  bigint not null references public.products(id) on delete cascade,
  user_id     uuid references public.profiles(id) on delete set null,
  author      text not null default 'Verified Buyer',
  rating      smallint not null check (rating between 1 and 5),
  text        text not null check (length(btrim(text)) > 0),
  status      text not null default 'Pending' check (status in ('Pending', 'Approved', 'Hidden')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index product_reviews_product_idx on public.product_reviews (product_id, status);
create unique index product_reviews_one_per_user on public.product_reviews (product_id, user_id) where user_id is not null;
create trigger product_reviews_updated_at before update on public.product_reviews
  for each row execute function public.set_updated_at();

-- -------------------------------------------------- cart / wishlist / address
create table public.cart_items (
  user_id     uuid   not null references public.profiles(id) on delete cascade,
  product_id  bigint not null references public.products(id) on delete cascade,
  qty         integer not null check (qty between 1 and 99),
  updated_at  timestamptz not null default now(),
  primary key (user_id, product_id)
);
create trigger cart_items_updated_at before update on public.cart_items
  for each row execute function public.set_updated_at();

create table public.wishlist_items (
  user_id     uuid   not null references public.profiles(id) on delete cascade,
  product_id  bigint not null references public.products(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.addresses (
  id          bigint generated always as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  label       text not null default '',
  line1       text not null check (length(btrim(line1)) > 0),
  city        text not null check (length(btrim(city)) > 0),
  pincode     text not null check (pincode ~ '^[0-9]{6}$'),
  phone       text check (phone is null or phone ~ '^[0-9]{10}$'),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index addresses_user_idx on public.addresses (user_id);
create trigger addresses_updated_at before update on public.addresses
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------- coupons
create table public.coupons (
  id            bigint generated always as identity primary key,
  code          text not null check (code = upper(btrim(code)) and length(code) > 0),
  type          text not null check (type in ('percentage', 'fixed')),
  value         numeric(10,2) not null check (value > 0),
  min_order     numeric(10,2) not null default 0 check (min_order >= 0),
  max_discount  numeric(10,2) not null check (max_discount >= 0),
  expiry        date not null,                -- valid through the end of this day
  usage_limit   integer not null check (usage_limit >= 0),
  used_count    integer not null default 0 check (used_count >= 0),
  status        text not null default 'Active' check (status in ('Active', 'Inactive', 'Expired')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index coupons_code_uq on public.coupons (code);
create trigger coupons_updated_at before update on public.coupons
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ orders
create sequence public.order_number_seq start 10000001;
create sequence public.return_number_seq start 3001;

create table public.orders (
  id               bigint generated always as identity primary key,
  -- same "SC" + 8 digits format as the old client-generated ids
  order_number     text not null unique default ('SC' || nextval('public.order_number_seq')),
  user_id          uuid references public.profiles(id) on delete set null,
  status           text not null default 'Pending' check (status in (
                     'Pending','Confirmed','Processing','Packed','Shipped',
                     'Out for Delivery','Delivered','Cancelled','Returned')),
  subtotal         numeric(10,2) not null check (subtotal >= 0),
  delivery_fee     numeric(10,2) not null default 0 check (delivery_fee >= 0),
  savings          numeric(10,2) not null default 0 check (savings >= 0),
  coupon_code      text,
  coupon_discount  numeric(10,2) not null default 0 check (coupon_discount >= 0),
  total            numeric(10,2) not null check (total >= 0),
  ship_name        text not null,
  ship_email       text not null,
  ship_phone       text not null check (ship_phone ~ '^[0-9]{10}$'),
  ship_line1       text not null,
  ship_city        text not null,
  ship_pincode     text not null check (ship_pincode ~ '^[0-9]{6}$'),
  stock_restored   boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index orders_user_idx    on public.orders (user_id, created_at desc);
create index orders_status_idx  on public.orders (status);
create index orders_created_idx on public.orders (created_at desc);
create trigger orders_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

create table public.order_items (
  id          bigint generated always as identity primary key,
  order_id    bigint not null references public.orders(id) on delete cascade,
  product_id  bigint references public.products(id) on delete set null,
  name        text not null,             -- snapshots: survive product edits/deletes
  image       text not null default '',
  price       numeric(10,2) not null check (price >= 0),
  qty         integer not null check (qty > 0)
);
create index order_items_order_idx   on public.order_items (order_id);
create index order_items_product_idx on public.order_items (product_id);
create unique index order_items_one_per_product on public.order_items (order_id, product_id) where product_id is not null;

create table public.order_status_history (
  id          bigint generated always as identity primary key,
  order_id    bigint not null references public.orders(id) on delete cascade,
  status      text not null,
  changed_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index order_status_history_order_idx on public.order_status_history (order_id, created_at);

create table public.coupon_redemptions (
  id           bigint generated always as identity primary key,
  coupon_id    bigint not null references public.coupons(id) on delete cascade,
  order_id     bigint not null unique references public.orders(id) on delete cascade,
  user_id      uuid references public.profiles(id) on delete set null,
  discount     numeric(10,2) not null,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- payments
-- Provider columns are empty until the Razorpay stage. No card data is ever stored.
create table public.payments (
  id                   bigint generated always as identity primary key,
  order_id             bigint not null references public.orders(id) on delete cascade,
  method               text not null check (method in ('card', 'upi', 'cod')),
  status               text not null default 'Pending' check (status in ('Pending', 'Paid', 'Failed', 'Refunded')),
  amount               numeric(10,2) not null check (amount >= 0),
  provider             text,                -- e.g. 'razorpay'
  provider_order_id    text,
  provider_payment_id  text,
  paid_at              timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index payments_order_idx  on public.payments (order_id);
create index payments_status_idx on public.payments (status);
create unique index payments_provider_payment_uq on public.payments (provider_payment_id) where provider_payment_id is not null;
create trigger payments_updated_at before update on public.payments
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------- returns
create table public.returns (
  id             bigint generated always as identity primary key,
  return_number  text not null unique default ('RET' || nextval('public.return_number_seq')),
  order_id       bigint not null references public.orders(id) on delete cascade,
  order_item_id  bigint references public.order_items(id) on delete set null,
  user_id        uuid references public.profiles(id) on delete set null,
  reason         text not null check (length(btrim(reason)) > 0),
  amount         numeric(10,2) not null check (amount >= 0),
  status         text not null default 'Requested' check (status in ('Requested', 'Approved', 'Rejected', 'Completed')),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index returns_order_idx on public.returns (order_id);
create index returns_user_idx  on public.returns (user_id);
create trigger returns_updated_at before update on public.returns
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------- site_settings
create table public.site_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);
create trigger site_settings_updated_at before update on public.site_settings
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- views
-- security_invoker: the views run with the caller's RLS, they don't bypass it.
create view public.catalog_products with (security_invoker = true) as
select
  p.id, p.name, p.title, p.price, p.discount_percent, p.original_price, p.image,
  p.category_id, c.name as category, p.stock_count, p.specs,
  p.is_best_seller, p.is_trending, p.is_active, p.created_at, p.updated_at,
  case when p.base_review_count + coalesce(r.n, 0) = 0 then 0
       else round((p.base_rating * p.base_review_count + coalesce(r.total, 0))
                  / (p.base_review_count + coalesce(r.n, 0)), 1)
  end as rating,
  p.base_review_count + coalesce(r.n, 0) as review_count
from public.products p
join public.categories c on c.id = p.category_id
left join (
  select product_id, count(*) as n, sum(rating) as total
  from public.product_reviews where status = 'Approved' group by product_id
) r on r.product_id = p.id;

-- Customer list for the admin panel: profile + real order aggregates.
create view public.admin_customers with (security_invoker = true) as
select
  pr.id, pr.name, pr.email, pr.phone, pr.status, pr.role, pr.created_at as joined,
  coalesce(o.orders, 0)       as orders,
  coalesce(o.total_spent, 0)  as total_spent,
  o.last_order_at,
  (select ship_city from public.orders x where x.user_id = pr.id order by x.created_at desc limit 1) as city
from public.profiles pr
left join (
  select user_id, count(*) as orders,
         sum(total) filter (where status not in ('Cancelled', 'Returned')) as total_spent,
         max(created_at) as last_order_at
  from public.orders where user_id is not null group by user_id
) o on o.user_id = pr.id;
