-- SmartCart: seed / migration of the existing application data (Phase 3)
-- Source: frontend/src/assets/list.json (+ values previously generated by
-- buildProduct() in data/products.js, frozen here) and the default coupons /
-- promo banner from data/coupons.js and data/promotions.js.
-- NOT migrated on purpose: fake demo customers, synthetic orders, payments,
-- returns, analytics and generated reviews (they were never real).
-- Idempotent: safe to run more than once.

insert into public.categories (name, icon, description, status, sort_order) values
  ('under 40 rupee', '🥪', 'Delicious picks from our under 40 rupee range.', 'Active', 1),
  ('premium sandwiches', '🍔', 'Delicious picks from our premium sandwiches range.', 'Active', 2),
  ('egg specials', '🍳', 'Delicious picks from our egg specials range.', 'Active', 3),
  ('vegetarian specials', '🥗', 'Delicious picks from our vegetarian specials range.', 'Active', 4),
  ('non-veg specials', '🍗', 'Delicious picks from our non-veg specials range.', 'Active', 5)
on conflict (lower(name)) do nothing;

insert into public.products
  (id, name, title, price, discount_percent, image, category_id, stock_count,
   base_rating, base_review_count, specs, is_best_seller, is_trending, is_active)

values
  (1, 'Classic Veg Sandwich', 'Fresh vegetable sandwich with mint chutney', 35, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('under 40 rupee')), 23, 4, 183, '{"Weight":"150g","Calories":"280 kcal","Prep Time":"5 min","Allergens":"Gluten, Dairy"}'::jsonb, false, false, true),
  (2, 'Grilled Cheese', 'Melted cheese between toasted bread slices', 40, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('under 40 rupee')), 28, 4.2, 248, '{"Weight":"150g","Calories":"280 kcal","Prep Time":"5 min","Allergens":"Gluten, Dairy"}'::jsonb, false, false, true),
  (3, 'Chicken Mayo', 'chicken with mayonnaise and veggies', 55, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('premium sandwiches')), 11, 4, 237, '{"Weight":"220g","Calories":"410 kcal","Prep Time":"8 min","Allergens":"Gluten, Dairy, Egg"}'::jsonb, true, false, true),
  (4, 'Egg Salad Sandwich', 'Boiled eggs with mayo and seasoning', 45, 32, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('egg specials')), 20, 4.8, 81, '{"Weight":"180g","Calories":"320 kcal","Prep Time":"6 min","Allergens":"Gluten, Egg"}'::jsonb, false, true, true),
  (5, 'Paneer Tikka', 'Grilled cottage cheese with tikka masala', 50, 32, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('vegetarian specials')), 0, 4, 235, '{"Weight":"170g","Calories":"260 kcal","Prep Time":"6 min","Allergens":"Gluten, Dairy"}'::jsonb, false, false, true),
  (6, 'Club Sandwich', 'Triple decker with chicken, egg and veggies', 65, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('premium sandwiches')), 42, 4.4, 195, '{"Weight":"220g","Calories":"410 kcal","Prep Time":"8 min","Allergens":"Gluten, Dairy, Egg"}'::jsonb, true, false, true),
  (7, 'Bombay Masala', 'Spicy potato filling with chutneys', 30, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('under 40 rupee')), 33, 4.4, 46, '{"Weight":"150g","Calories":"280 kcal","Prep Time":"5 min","Allergens":"Gluten, Dairy"}'::jsonb, false, false, true),
  (8, 'Tuna Salad', 'Tuna fish with mayo and celery', 70, 13, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('premium sandwiches')), 27, 3.9, 35, '{"Weight":"220g","Calories":"410 kcal","Prep Time":"8 min","Allergens":"Gluten, Dairy, Egg"}'::jsonb, false, true, true),
  (9, 'Aloo Grilled', 'Spiced potato filling grilled to perfection', 35, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('under 40 rupee')), 25, 3.9, 157, '{"Weight":"150g","Calories":"280 kcal","Prep Time":"5 min","Allergens":"Gluten, Dairy"}'::jsonb, true, false, true),
  (10, 'Chicken Tikka', 'Grilled chicken tikka pieces with onions', 60, 0, 'https://images.pexels.com/photos/3761662/pexels-photo-3761662.jpeg?auto=compress&cs=tinysrgb&w=500', (select id from public.categories where lower(name) = lower('non-veg specials')), 10, 4.6, 259, '{"Weight":"210g","Calories":"390 kcal","Prep Time":"9 min","Allergens":"Gluten, Dairy"}'::jsonb, false, false, true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));

-- Coupons (used_count starts at 0: the old counts were fake demo numbers).
insert into public.coupons (code, type, value, min_order, max_discount, expiry, usage_limit, used_count, status) values
  ('WELCOME10',  'percentage', 10, 50,  30, '2026-12-31',  500, 0, 'Active'),
  ('FLAT20',     'fixed',      20, 100, 20, '2026-10-31',  200, 0, 'Active'),
  ('SANDWICH50', 'percentage', 50, 30,  25, '2026-09-15',  100, 0, 'Expired'),
  ('FREESHIP',   'fixed',      25, 0,   25, '2027-01-31', 1000, 0, 'Active')
on conflict (code) do nothing;

-- Site settings
insert into public.site_settings (key, value) values
  ('promo_banner', '{"title":"Craving something new? Explore the full menu.","description":"From budget bites to premium picks, there''s a sandwich for every mood.","ctaText":"Explore Menu","ctaLink":"/menu","active":true}'::jsonb),
  ('delivery',     '{"fee": 25, "free_above": 200}'::jsonb),
  ('store',        '{"name": "SmartCart", "currency": "INR", "support_email": "support@smartcart.com"}'::jsonb)
on conflict (key) do nothing;
